version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      challenge_network:
        aliases:
          - backend_alias

  database:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    networks:
      challenge_network:
        aliases:
          - db_alias

networks:
  challenge_network:
    driver: bridge
